// ⚠ Généré avec scripts/generer-noms-avatar.mts — ne pas éditer à la main.
//
// Libellés des options d'avatar, séparés de `atomes.ts` pour que le client
// puisse nommer chaque vignette sans embarquer les 566 Ko de tracés.

import type { Categorie } from '@/lib/avatar/tailles'

export const NOMS_OPTIONS: Record<Categorie, string[]> = {
  tenue: [
    "Blazer et t-shirt",
    "Chemise boutonnée",
    "Chemise à motifs",
    "Tasse à la main",
    "Téléphone à la main",
    "Robe",
    "En pleine explication",
    "Veste épaisse",
    "Manette en main",
    "Débardeur",
  ],
  coiffure: [
    "Afro",
    "Frange dégradée",
    "Frange",
    "Nœuds bantous",
    "Cheveux ébouriffés",
    "Chignon haut",
    "Chignon",
    "Deux chignons",
    "Tresses collées",
    "Cornrows",
    "Coupe carrée longue",
    "Coupe carrée",
    "Chignon grisonnant",
    "Mi-longs grisonnants",
    "Courts grisonnants",
    "Foulard",
    "Afro long",
    "Longs à frange",
    "Longs bouclés",
    "Cheveux longs",
    "Mi-longs",
    "Mi-longs ondulés",
    "Mi-longs volumineux",
    "Mi-longs à frange",
  ],
  visage: [
    "Contrarié",
    "Émerveillé",
    "Neutre",
    "Serein",
    "Malicieux",
    "Inquiet",
    "Soucieux",
    "Dubitatif",
    "Doux",
    "Rêveur",
    "Déterminé",
    "Gourmand",
    "En pleine explication",
    "Yeux fermés",
    "Surpris",
    "Débordé",
    "Grand sourire",
    "Sourire complice",
    "Espiègle",
    "Sage",
  ],
  pilosite: [
    "Aucune",
    "Bouc au menton",
    "Barbe fournie",
    "Barbe taillée",
    "Barbe longue",
    "Barbe pleine",
    "Bouc",
    "Bouc fin",
    "Moustache",
    "Moustache fine",
    "Moustache épaisse",
    "Moustache large",
  ],
  accessoire: [
    "Aucune",
    "Cache-œil",
    "Lunettes rondes",
    "Lunettes fines",
    "Lunettes carrées",
    "Lunettes épaisses",
    "Lunettes",
    "Lunettes de soleil rondes",
    "Lunettes de soleil",
  ],
}

export const LIBELLES_CATEGORIES: Record<Categorie, string> = {
  tenue: "Tenue",
  coiffure: "Coiffure",
  visage: "Expression",
  pilosite: "Barbe",
  accessoire: "Lunettes",
}
